# Generated by Django 2.2.28 on 2023-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=200)),
                ('purpose', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('unit', models.CharField(help_text='Unit of Med', max_length=100, verbose_name='Unit')),
                ('dosage', models.CharField(help_text='Unit of Med', max_length=100, verbose_name='Unit')),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
