# Generated by Django 2.2.28 on 2023-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('doc_spec', models.TextField(help_text='Enter a brief description', max_length=250)),
                ('dep_name', models.CharField(help_text='Enter the unit of Med', max_length=100, verbose_name='department')),
                ('doc_image', models.ImageField(upload_to='doctors')),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(help_text='Dosage of Med', max_length=100, verbose_name='dosage'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Availability', null=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(help_text='Enter the unit of Med', max_length=100, verbose_name='Unit'),
        ),
    ]
