# Generated by Django 2.2.28 on 2023-07-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_site', '0002_auto_20230715_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='dep_name',
            field=models.CharField(help_text='Enter the department', max_length=100, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_spec',
            field=models.TextField(help_text='Enter a doctors specialization', max_length=250),
        ),
    ]
